// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUFD1yePJsGLHDTN6tYX-J7VZ4jKuCIk',
    appId: '1:21742878040:web:0a8fac36700da5a965792d',
    messagingSenderId: '21742878040',
    projectId: 'expense-ai-229de',
    authDomain: 'expense-ai-229de.firebaseapp.com',
    storageBucket: 'expense-ai-229de.firebasestorage.app',
    measurementId: 'G-PZQKZX631Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXQ9TPLFqOskogfrTBwYHG3GsrP1TW78M',
    appId: '1:21742878040:android:97c5ee4c7cf2472365792d',
    messagingSenderId: '21742878040',
    projectId: 'expense-ai-229de',
    storageBucket: 'expense-ai-229de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQKaD3M7LOJFzU0iNr9SkMlddN7FC9cY',
    appId: '1:21742878040:ios:b7092a9c86c3cb5865792d',
    messagingSenderId: '21742878040',
    projectId: 'expense-ai-229de',
    storageBucket: 'expense-ai-229de.firebasestorage.app',
    iosClientId: '21742878040-mpl3rlh4tlhjan5l6i5rnkr034kbpanr.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQKaD3M7LOJFzU0iNr9SkMlddN7FC9cY',
    appId: '1:21742878040:ios:b7092a9c86c3cb5865792d',
    messagingSenderId: '21742878040',
    projectId: 'expense-ai-229de',
    storageBucket: 'expense-ai-229de.firebasestorage.app',
    iosClientId: '21742878040-mpl3rlh4tlhjan5l6i5rnkr034kbpanr.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUFD1yePJsGLHDTN6tYX-J7VZ4jKuCIk',
    appId: '1:21742878040:web:b21583685524e7b065792d',
    messagingSenderId: '21742878040',
    projectId: 'expense-ai-229de',
    authDomain: 'expense-ai-229de.firebaseapp.com',
    storageBucket: 'expense-ai-229de.firebasestorage.app',
    measurementId: 'G-HBGDDQC885',
  );

}